name: eco_bin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  flutter_riverpod: ^3.3.1
  fl_chart: ^1.1.1
  google_fonts: ^8.0.2
  intl: ^0.20.2
  font_awesome_flutter: ^11.0.0
  mobile_scanner: ^6.0.4
  qr_flutter: ^4.1.0
  http: ^1.2.1
  app_links: ^6.4.1
  shared_preferences: ^2.5.4
  flutter_local_notifications: ^17.2.2
  audioplayers: ^6.1.0
  geolocator: ^13.0.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/smart_bin_hero.png
    - assets/sounds/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_background: "#1B5E20"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
